### ISSUE TITLE
In release notes replace all those `...by @mergify` with actual author

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#216]
When mergify backports a PR it will always show as `... by @mergify` in the release notes. That's a bit annoying since the actual author does not get credit and his/her profile pic will not show up at the bottom of the release notes.
Actually we could fix that to make mergify include the author in the title, so in [the mergify config we would have to add](https://docs.mergify.com/actions/backport/):

```
defaults:
    actions:
      backport:
        title:
          - "{{ title }} (backport #{{ number }}) by {{ author }}"
```

Plus we would have to make release-drafter remove all ` by @mergify` occurences, that should be possible by using replacers: https://github.com/release-drafter/release-drafter/#replacers

Also see https://github.com/playframework/playframework/issues/10965
